server {
    listen 80;
    server_name morethanparrots.com www.morethanparrots.com;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        alias /var/www/mtp/staticfiles/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    location /media/ {
        alias /var/www/mtp/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn/gunicorn.sock;
    }
}
